runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

beta_settings:
     cloud_sql_instances: "the-ship-that-always-stinks:europe-west1:ship-that-stinks"