"""empty message

Revision ID: 0f1e3e3da01d
Revises: 3d070744255e
Create Date: 2019-10-29 09:40:43.368079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1e3e3da01d'
down_revision = '3d070744255e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_events_id', table_name='event_events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_event_events_id', 'event_events', ['id'], unique=False)
    # ### end Alembic commands ###
