"""empty message

Revision ID: 31e3b6e7e196
Revises: 759946a0d52c
Create Date: 2019-10-28 15:31:28.875463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e3b6e7e196'
down_revision = '759946a0d52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=False))
    op.drop_constraint('users_nickname_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_nickname_key', 'users', ['nickname'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
