"""empty message

Revision ID: 390e9b20b5f8
Revises: c4b0fdfca7b5
Create Date: 2019-10-27 19:00:54.461164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390e9b20b5f8'
down_revision = 'c4b0fdfca7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_event_id', table_name='attendance')
    op.drop_constraint('attendance_event_id_fkey', 'attendance', type_='foreignkey')
    op.drop_index('ix_event_events_event_id', table_name='event_events')
    op.drop_constraint('events_event_id_fkey', 'event_events', type_='foreignkey')
    op.drop_index('ix_proposal_responses_event_id', table_name='proposal_responses')
    op.drop_constraint('proposal_responses_event_id_fkey', 'proposal_responses', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('proposal_responses_event_id_fkey', 'proposal_responses', 'events', ['event_id'], ['id'])
    op.create_index('ix_proposal_responses_event_id', 'proposal_responses', ['event_id'], unique=False)
    op.create_foreign_key('events_event_id_fkey', 'event_events', 'events', ['event_id'], ['id'])
    op.create_index('ix_event_events_event_id', 'event_events', ['event_id'], unique=False)
    op.create_foreign_key('attendance_event_id_fkey', 'attendance', 'events', ['event_id'], ['id'])
    op.create_index('ix_attendance_event_id', 'attendance', ['event_id'], unique=False)
    # ### end Alembic commands ###
