"""empty message

Revision ID: 3d070744255e
Revises: 39818e8a159f
Create Date: 2019-10-28 15:54:49.636679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d070744255e'
down_revision = '39818e8a159f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_events', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('event_events', 'update_created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_events', sa.Column('update_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('event_events', 'created_at')
    # ### end Alembic commands ###
