"""empty message

Revision ID: 4053e6b07106
Revises: c3626c40ff53
Create Date: 2019-11-03 21:26:08.720127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4053e6b07106'
down_revision = 'c3626c40ff53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_events_organised_by', table_name='event_events')
    op.drop_constraint('event_events_organised_by_fkey', 'event_events', type_='foreignkey')
    op.drop_column('event_events', 'attendee_mult')
    op.drop_column('event_events', 'points_pp')
    op.drop_column('event_events', 'notice_days')
    op.drop_column('event_events', 'notice_mult')
    op.drop_column('event_events', 'has_happened')
    op.drop_column('event_events', 'attendee_cnt')
    op.drop_column('event_events', 'organised_by')
    op.alter_column('events', 'notice_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'notice_mult',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'notice_mult',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('events', 'notice_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('event_events', sa.Column('organised_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event_events', sa.Column('attendee_cnt', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event_events', sa.Column('has_happened', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('event_events', sa.Column('notice_mult', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('event_events', sa.Column('notice_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event_events', sa.Column('points_pp', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('event_events', sa.Column('attendee_mult', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('event_events_organised_by_fkey', 'event_events', 'users', ['organised_by'], ['id'])
    op.create_index('ix_event_events_organised_by', 'event_events', ['organised_by'], unique=False)
    # ### end Alembic commands ###
