"""differentiated date, time

Revision ID: 5985ed3ce25c
Revises: 
Create Date: 2019-08-15 16:40:24.227837

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5985ed3ce25c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipmates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipmates_first_name'), 'shipmates', ['first_name'], unique=False)
    op.create_index(op.f('ix_shipmates_nickname'), 'shipmates', ['nickname'], unique=True)
    op.create_index(op.f('ix_shipmates_surname'), 'shipmates', ['surname'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=False),
    sa.Column('event_location', sa.String(length=128), nullable=True),
    sa.Column('event_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organised_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organised_by'], ['shipmates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_event_name'), 'events', ['event_name'], unique=False)
    op.create_index(op.f('ix_events_event_status'), 'events', ['event_status'], unique=False)
    op.create_index(op.f('ix_events_event_time'), 'events', ['event_time'], unique=False)
    op.create_table('proposal_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_datetime', sa.DateTime(), nullable=False),
    sa.Column('response', sa.String(length=32), nullable=False),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('shipmate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event'], ['events.id'], ),
    sa.ForeignKeyConstraint(['shipmate'], ['shipmates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_response_response'), 'proposal_response', ['response'], unique=False)
    op.create_index(op.f('ix_proposal_response_response_datetime'), 'proposal_response', ['response_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_response_response_datetime'), table_name='proposal_response')
    op.drop_index(op.f('ix_proposal_response_response'), table_name='proposal_response')
    op.drop_table('proposal_response')
    op.drop_index(op.f('ix_events_event_time'), table_name='events')
    op.drop_index(op.f('ix_events_event_status'), table_name='events')
    op.drop_index(op.f('ix_events_event_name'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_shipmates_surname'), table_name='shipmates')
    op.drop_index(op.f('ix_shipmates_nickname'), table_name='shipmates')
    op.drop_index(op.f('ix_shipmates_first_name'), table_name='shipmates')
    op.drop_table('shipmates')
    # ### end Alembic commands ###
