"""empty message

Revision ID: 8e9a6229825e
Revises: 31e3b6e7e196
Create Date: 2019-10-28 15:44:28.084259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9a6229825e'
down_revision = '31e3b6e7e196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_events', 'is_confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_events', sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
