"""empty message

Revision ID: bbd15a503817
Revises: 68b24a4c9777
Create Date: 2019-11-03 15:54:50.861484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbd15a503817'
down_revision = '68b24a4c9777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_events', 'notice_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('event_events', 'notice_mult',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('events', sa.Column('attendee_cnt', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('attendee_mult', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('has_happened', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('points_pp', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'points_pp')
    op.drop_column('events', 'has_happened')
    op.drop_column('events', 'attendee_mult')
    op.drop_column('events', 'attendee_cnt')
    op.alter_column('event_events', 'notice_mult',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('event_events', 'notice_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
