"""empty message

Revision ID: c49f4bc2f790
Revises: d8e7cbb8f617
Create Date: 2019-10-21 12:16:06.571756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49f4bc2f790'
down_revision = 'd8e7cbb8f617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_ids', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_ids', 'created_at')
    # ### end Alembic commands ###
