"""empty message

Revision ID: c4b0fdfca7b5
Revises: e0c1cc10a41e
Create Date: 2019-10-27 10:23:14.251576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b0fdfca7b5'
down_revision = 'e0c1cc10a41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attendance_event_id_fkey', 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'events', ['event_id'], ['id'])
    op.create_index(op.f('ix_event_events_event_id'), 'event_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_events_id'), 'event_events', ['id'], unique=False)
    op.create_index(op.f('ix_event_events_organised_by'), 'event_events', ['organised_by'], unique=False)
    op.drop_index('ix_events_event_id', table_name='event_events')
    op.drop_index('ix_events_id', table_name='event_events')
    op.drop_index('ix_events_organised_by', table_name='event_events')
    op.alter_column('events', 'organised_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_organised_by'), 'events', ['organised_by'], unique=False)
    op.drop_index('ix_event_ids_id', table_name='events')
    op.drop_index('ix_event_ids_organised_by', table_name='events')
    op.drop_constraint('proposal_responses_event_fkey', 'proposal_responses', type_='foreignkey')
    op.create_foreign_key(None, 'proposal_responses', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposal_responses', type_='foreignkey')
    op.create_foreign_key('proposal_responses_event_fkey', 'proposal_responses', 'event_events', ['event_id'], ['id'])
    op.create_index('ix_event_ids_organised_by', 'events', ['organised_by'], unique=False)
    op.create_index('ix_event_ids_id', 'events', ['id'], unique=False)
    op.drop_index(op.f('ix_events_organised_by'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.alter_column('events', 'organised_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_events_organised_by', 'event_events', ['organised_by'], unique=False)
    op.create_index('ix_events_id', 'event_events', ['id'], unique=False)
    op.create_index('ix_events_event_id', 'event_events', ['event_id'], unique=False)
    op.drop_index(op.f('ix_event_events_organised_by'), table_name='event_events')
    op.drop_index(op.f('ix_event_events_id'), table_name='event_events')
    op.drop_index(op.f('ix_event_events_event_id'), table_name='event_events')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_event_id_fkey', 'attendance', 'event_events', ['event_id'], ['id'])
    # ### end Alembic commands ###
