"""empty message

Revision ID: db4789b3d7d4
Revises: 0f1e3e3da01d
Create Date: 2019-10-29 09:45:31.877409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4789b3d7d4'
down_revision = '0f1e3e3da01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_events_id'), 'event_events', ['id'], unique=False)
    op.drop_index('ix_events_id', table_name='events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.drop_index(op.f('ix_event_events_id'), table_name='event_events')
    # ### end Alembic commands ###
