"""empty message

Revision ID: e0c1cc10a41e
Revises: c49f4bc2f790
Create Date: 2019-10-21 15:01:43.462279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c1cc10a41e'
down_revision = 'c49f4bc2f790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_ids', sa.Column('organised_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_event_ids_organised_by'), 'event_ids', ['organised_by'], unique=False)
    op.create_foreign_key(None, 'event_ids', 'users', ['organised_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_ids', type_='foreignkey')
    op.drop_index(op.f('ix_event_ids_organised_by'), table_name='event_ids')
    op.drop_column('event_ids', 'organised_by')
    # ### end Alembic commands ###
