"""empty message

Revision ID: fe50e3ba3b93
Revises: 
Create Date: 2020-01-15 20:20:52.255612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe50e3ba3b93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.Date(), nullable=False),
    sa.Column('end_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycles_id'), 'cycles', ['id'], unique=False)
    op.add_column('events', sa.Column('cycle_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_cycle_id'), 'events', ['cycle_id'], unique=False)
    op.create_foreign_key(None, 'events', 'cycles', ['cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_cycle_id'), table_name='events')
    op.drop_column('events', 'cycle_id')
    op.drop_index(op.f('ix_cycles_id'), table_name='cycles')
    op.drop_table('cycles')
    # ### end Alembic commands ###
